package org.andersenlab.tests;// Generated by Selenium IDE

import org.andersenlab.helpers.HomePage;
import org.junit.Test;
import org.openqa.selenium.WebDriver;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;

public class AutorizationTest extends TestBase {
    private WebDriver driver;
    private HomePage homePage;
    private Properties properties;
    private HomePage homePageNew;

    @Test
    public void autorization() throws IOException {
        driver = super.driver;
        properties = new Properties();
        properties.load(new FileReader(new File("src/main/resources/local.properties")));
        homePage = new HomePage(driver);
        homePageNew = homePage.clickSignIn()
                .setUsername(properties.getProperty("web.username"))
                .setPassword(properties.getProperty("web.password"))
                .clickCommitButton();

        assert (homePageNew.isHomePageAppear() == 1);
    }
}
