package org.andersenlab.tests;// Generated by Selenium IDE

import org.andersenlab.helpers.CreatedProjectPage;
import org.andersenlab.helpers.HomePage;
import org.junit.Test;
import org.openqa.selenium.WebDriver;

import java.io.File;
import java.io.FileReader;
import java.io.IOException;
import java.util.Properties;

import static org.junit.Assert.assertEquals;

public class ProjectCreationTest extends TestBase {
    private WebDriver driver;
    private HomePage homePage;
    private Properties properties;
    private CreatedProjectPage createdProjectPage;


    @Test
    public void projectCreation() throws IOException {
        driver = super.driver;
        properties = new Properties();
        properties.load(new FileReader(new File("src/main/resources/local.properties")));
        homePage = new HomePage(driver);
        CharSequence uniqueName = "aData_" + System.currentTimeMillis();
        createdProjectPage = homePage.clickSignIn()
                .setUsername(properties.getProperty("web.username"))
                .setPassword(properties.getProperty("web.password"))
                .clickCommitButton()
                .selectNewProject()
                .createProject(uniqueName);
        assertEquals(uniqueName, createdProjectPage.getActualTitle());
    }
}
